"""Signal engine schemas."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """Ranked signal generated by L5."""

    strategy_id: str
    strategy_version: str
    signal_date: str
    stock_code: str
    triggered_labels: tuple[str, ...]
    recall_reasons: tuple[str, ...]
    passed_filters: tuple[str, ...]
    ranking_score: float
    rank: int
    warning_checks: tuple[str, ...] = field(default_factory=tuple)
